server:
  port: 8001

# 这里的classpath就是指向resources目录下的文件
mybatis:
  type-aliases-package: com.keqi.springcloud.pojo
  # mybatis 核心配置
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper 配置
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    # 项目名字
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yiing123

#Eureka,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 修改eureka上的默认显示信息
    instance-id: springcloud-provider-dept8001

# info 配置
info:
  app.name: com.keqi
  company.name: hb